/**
 * Korean slug generation utility
 * 한글 슬러그 생성 유틸리티
 */

/**
 * Generate URL-safe English slug from Korean text
 * Creates readable English slugs from Korean titles
 */
export function generateKoreanSlug(text: string): string {
  if (!text) return ''
  
  // Common Korean to English mappings for startup/tech content
  const koreanToEnglish: Record<string, string> = {
    '스타트업': 'startup',
    '창업자': 'entrepreneur',
    '창업': 'entrepreneurship',
    '법칙': 'rules',
    '가지': 'things',
    '알아야': 'should-know',
    '할': 'to',
    '성공': 'success',
    '실패': 'failure',
    '투자': 'investment',
    '비즈니스': 'business',
    '모델': 'model',
    '전략': 'strategy',
    '마케팅': 'marketing',
    '성장': 'growth',
    '개발': 'development',
    '기술': 'technology',
    '혁신': 'innovation',
    '디지털': 'digital',
    '플랫폼': 'platform',
    '서비스': 'service',
    '고객': 'customer',
    '사용자': 'user',
    '경험': 'experience',
    '데이터': 'data',
    '분석': 'analysis',
    '트렌드': 'trend',
    '시장': 'market',
    '경쟁': 'competition',
    '차별화': 'differentiation',
    '가치': 'value',
    '제안': 'proposition',
    '수익': 'revenue',
    '확장': 'scaling',
    '글로벌': 'global',
    '로컬': 'local',
    '커뮤니티': 'community',
    '네트워크': 'network',
    '파트너': 'partner',
    '협업': 'collaboration',
    '리더십': 'leadership',
    '팀': 'team',
    '문화': 'culture',
    '조직': 'organization',
    '운영': 'operation',
    '효율': 'efficiency',
    '자동화': 'automation',
    '인공지능': 'ai',
    '블록체인': 'blockchain',
    '핀테크': 'fintech',
    '이커머스': 'ecommerce',
    '소셜': 'social',
    '미디어': 'media',
    '콘텐츠': 'content',
    '브랜드': 'brand',
    '아이덴티티': 'identity',
    '프로덕트': 'product',
    '솔루션': 'solution',
    '최적화': 'optimization',
    '전환': 'conversion',
    '지표': 'metrics',
    '디자인': 'design',
    '프로토타입': 'prototype',
    '테스트': 'test',
    '피드백': 'feedback',
    '개선': 'improvement',
    '업데이트': 'update',
    '릴리즈': 'release',
    '버전': 'version',
    '보안': 'security',
    '백엔드': 'backend',
    '프론트엔드': 'frontend',
    '풀스택': 'fullstack',
    '클라우드': 'cloud',
    '서버': 'server',
    '데이터베이스': 'database',
    '인프라': 'infrastructure',
    '스케일': 'scale',
    '모니터링': 'monitoring',
    '대시보드': 'dashboard',
    '리포트': 'report',
    '인사이트': 'insight',
    '의사결정': 'decision-making',
    '전략적': 'strategic',
    '전술적': 'tactical',
    '실행': 'execution',
    '계획': 'planning',
    '로드맵': 'roadmap',
    '마일스톤': 'milestone',
    '목표': 'goal',
    '비전': 'vision',
    '미션': 'mission',
    '가치관': 'values',
    '핵심': 'core',
    '경쟁력': 'competitiveness',
    '차별점': 'differentiator',
    '강점': 'strength',
    '약점': 'weakness',
    '기회': 'opportunity',
    '위협': 'threat',
    '시나리오': 'scenario',
    '예측': 'forecast',
    '예산': 'budget',
    '자금': 'funding',
    '투자자': 'investor',
    '엔젤': 'angel',
    '시리즈': 'series',
    '라운드': 'round',
    '밸류에이션': 'valuation',
    '엑싯': 'exit',
    '인수합병': 'merger-acquisition',
    '파트너십': 'partnership',
    '제휴': 'alliance',
    '계약': 'contract',
    '협상': 'negotiation',
    '거래': 'deal',
    '조건': 'terms',
    '약관': 'agreement',
    '라이선스': 'license',
    '특허': 'patent',
    '지적재산권': 'ip',
    '상표': 'trademark',
    '저작권': 'copyright',
    '법적': 'legal',
    '규제': 'regulation',
    '컴플라이언스': 'compliance',
    '윤리': 'ethics',
    '책임': 'responsibility',
    '지속가능': 'sustainable',
    '임팩트': 'impact',
    '사회적': 'social',
    '환경': 'environment',
    '거버넌스': 'governance',
    '이해관계자': 'stakeholder',
    '주주': 'shareholder',
    '직원': 'employee',
    '공급자': 'supplier',
    '경쟁사': 'competitor',
    '산업': 'industry',
    '섹터': 'sector',
    '버티컬': 'vertical',
    '호라이즌탈': 'horizontal',
    '통합': 'integration',
    '연동': 'connection',
    '동기화': 'sync',
    '실시간': 'realtime',
    '자동': 'automatic',
    '수동': 'manual',
    '프로세스': 'process',
    '워크플로우': 'workflow',
    '효율성': 'efficiency',
    '생산성': 'productivity',
    '성과': 'performance',
    '결과': 'result',
    '아웃풋': 'output',
    '인풋': 'input',
    '리소스': 'resource',
    '할당': 'allocation',
    '최적': 'optimal',
    '혁신': 'innovate',
    '변화': 'change',
    '디지털전환': 'digital-transformation',
    '여정': 'journey',
    '터치포인트': 'touchpoint',
    '채널': 'channel',
    '옴니채널': 'omnichannel',
    '멀티채널': 'multichannel',
    '크로스채널': 'crosschannel',
    '온라인': 'online',
    '오프라인': 'offline',
    '하이브리드': 'hybrid',
    '융합': 'convergence',
    '시너지': 'synergy',
    '레버리지': 'leverage',
    '스케일업': 'scaleup',
    '스케일아웃': 'scaleout',
    '그로스': 'growth',
    '해킹': 'hacking',
    '그로스해킹': 'growth-hacking',
    '바이럴': 'viral',
    '입소문': 'word-of-mouth',
    '추천': 'referral',
    '리텐션': 'retention',
    '이탈': 'churn',
    '활성': 'active',
    '비활성': 'inactive',
    '유저': 'user',
    '퍼널': 'funnel',
    '깔때기': 'funnel',
    '단계': 'stage',
    '스텝': 'step',
    '플로우': 'flow',
    '시퀀스': 'sequence',
    '개인화': 'personalization',
    '맞춤': 'custom',
    '커스텀': 'custom',
    '세그먼트': 'segment',
    '타겟': 'target',
    '타겟팅': 'targeting',
    '포지셔닝': 'positioning',
    '메시지': 'message',
    '메시징': 'messaging',
    '커뮤니케이션': 'communication',
    '브랜딩': 'branding',
    '광고': 'advertising',
    '홍보': 'pr',
    '캠페인': 'campaign',
    '프로모션': 'promotion',
    '이벤트': 'event',
    '할인': 'discount',
    '쿠폰': 'coupon',
    '포인트': 'point',
    '리워드': 'reward',
    '보상': 'reward',
    '인센티브': 'incentive',
    '동기부여': 'motivation',
    '참여': 'engagement',
    '인게이지먼트': 'engagement',
    '상호작용': 'interaction',
    '피드': 'feed',
    '알림': 'notification',
    '푸시': 'push',
    '이메일': 'email',
    '메신저': 'messenger',
    '챗봇': 'chatbot',
    '머신러닝': 'machine-learning',
    '딥러닝': 'deep-learning',
    '자연어': 'nlp',
    '컴퓨터비전': 'computer-vision',
    '음성인식': 'speech-recognition',
    '번역': 'translation',
    '요약': 'summary',
    '추출': 'extraction',
    '분류': 'classification',
    '예측': 'prediction',
    '추천': 'recommendation',
    '봇': 'bot',
    '에이전트': 'agent',
    '어시스턴트': 'assistant',
    '도우미': 'helper',
    '가이드': 'guide',
    '튜토리얼': 'tutorial',
    '온보딩': 'onboarding',
    '교육': 'education',
    '트레이닝': 'training',
    '학습': 'learning',
    '커리어': 'career',
    '경력': 'career',
    '스킬': 'skill',
    '역량': 'competency',
    '전문성': 'expertise',
    '노하우': 'knowhow',
    '사례': 'case',
    '케이스': 'case',
    '스터디': 'study',
    '연구': 'research',
    '조사': 'survey',
    '설문': 'questionnaire',
    '인터뷰': 'interview',
    '포커스그룹': 'focus-group',
    '관찰': 'observation',
    '실험': 'experiment',
    '테스팅': 'testing',
    '검증': 'validation',
    '증명': 'proof',
    '파일럿': 'pilot',
    '베타': 'beta',
    '알파': 'alpha',
    '프리뷰': 'preview',
    '얼리액세스': 'early-access',
    '런칭': 'launch',
    '출시': 'release',
    '공개': 'public',
    '비공개': 'private',
    '클로즈드': 'closed',
    '오픈': 'open',
    '정식': 'official',
    '업그레이드': 'upgrade',
    '다운그레이드': 'downgrade',
    '마이그레이션': 'migration',
    '이전': 'migration',
    '백업': 'backup',
    '복구': 'recovery',
    '암호화': 'encryption',
    '인증': 'authentication',
    '권한': 'authorization',
    '접근': 'access',
    '제어': 'control',
    '관리': 'management',
    '유지보수': 'maintenance',
    '로그': 'log',
    '추적': 'tracking',
    '리포팅': 'reporting',
    '시각화': 'visualization',
    '차트': 'chart',
    '그래프': 'graph',
    '테이블': 'table',
    '리스트': 'list',
    '그리드': 'grid',
    '카드': 'card',
    '타일': 'tile',
    '위젯': 'widget',
    '컴포넌트': 'component',
    '모듈': 'module',
    '플러그인': 'plugin',
    '익스텐션': 'extension',
    '애드온': 'addon',
    '라이브러리': 'library',
    '프레임워크': 'framework',
    '아키텍처': 'architecture',
    '설계': 'design',
    '구조': 'structure',
    '패턴': 'pattern',
    '모범사례': 'best-practice',
    '가이드라인': 'guideline',
    '원칙': 'principle',
    '정책': 'policy',
    '규칙': 'rule',
    '표준': 'standard',
    '프로토콜': 'protocol',
    '인터페이스': 'interface',
    '엔드포인트': 'endpoint',
    '라우트': 'route',
    '미들웨어': 'middleware',
    '핸들러': 'handler',
    '콜백': 'callback',
    '프로미스': 'promise',
    '비동기': 'async',
    '동기': 'sync',
    '병렬': 'parallel',
    '순차': 'sequential',
    '큐': 'queue',
    '스택': 'stack',
    '배치': 'batch',
    '스트림': 'stream',
    '웹소켓': 'websocket',
    '마이크로서비스': 'microservice',
    '모놀리식': 'monolithic',
    '서버리스': 'serverless',
    '컨테이너': 'container',
    '도커': 'docker',
    '쿠버네티스': 'kubernetes',
    '오케스트레이션': 'orchestration',
    '배포': 'deployment',
    '파이프라인': 'pipeline',
    '빌드': 'build',
    '스테이징': 'staging',
    '프로덕션': 'production',
    '설정': 'configuration',
    '변수': 'variable',
    '파라미터': 'parameter',
    '옵션': 'option',
    '플래그': 'flag',
    '토글': 'toggle',
    '스위치': 'switch',
    '모드': 'mode',
    '상태': 'state',
    '라이프사이클': 'lifecycle',
    '훅': 'hook',
    '리스너': 'listener',
    '트리거': 'trigger',
    '액션': 'action',
    '커맨드': 'command',
    '쿼리': 'query',
    '뮤테이션': 'mutation',
    '서브스크립션': 'subscription',
    '페이지네이션': 'pagination',
    '필터': 'filter',
    '정렬': 'sort',
    '검색': 'search',
    '인덱스': 'index',
    '캐시': 'cache',
    '세션': 'session',
    '쿠키': 'cookie',
    '토큰': 'token',
    '멀티팩터': 'mfa',
    '생체인증': 'biometric',
    '얼굴인식': 'face-recognition',
    '지문인식': 'fingerprint',
    '홍채인식': 'iris-recognition',
    '패스워드': 'password',
    '비밀번호': 'password',
    '인증서': 'certificate',
    '방화벽': 'firewall',
    '취약점': 'vulnerability',
    '패치': 'patch',
    '개인정보': 'privacy',
    '개인정보보호': 'privacy-protection',
    '익명화': 'anonymization',
    '가명화': 'pseudonymization',
    '복호화': 'decryption',
    '해시': 'hash',
    '솔트': 'salt',
    '키': 'key',
    '공개키': 'public-key',
    '비밀키': 'private-key',
    '대칭키': 'symmetric-key',
    '비대칭키': 'asymmetric-key',
    '인코딩': 'encoding',
    '디코딩': 'decoding',
    '압축': 'compression',
    '압축해제': 'decompression',
    '아카이브': 'archive',
    '복원': 'restore',
    '리플리케이션': 'replication',
    '미러링': 'mirroring',
    '클러스터': 'cluster',
    '로드밸런싱': 'load-balancing',
    '페일오버': 'failover',
    '이중화': 'redundancy',
    '가용성': 'availability',
    '확장성': 'scalability',
    '신뢰성': 'reliability',
    '내구성': 'durability',
    '일관성': 'consistency',
    '트랜잭션': 'transaction',
    '커밋': 'commit',
    '롤백': 'rollback',
    '락': 'lock',
    '데드락': 'deadlock',
    '동시성': 'concurrency',
    '병렬성': 'parallelism',
    '스레드': 'thread',
    '코루틴': 'coroutine',
    '파이버': 'fiber',
    '액터': 'actor',
    '브로커': 'broker',
    '퍼블리셔': 'publisher',
    '서브스크라이버': 'subscriber',
    '이벤트버스': 'event-bus',
    '메시지버스': 'message-bus',
    '관계형': 'relational',
    '비관계형': 'non-relational',
    '도큐먼트': 'document',
    '키밸류': 'key-value',
    '컬럼패밀리': 'column-family',
    '시계열': 'time-series',
    '벡터': 'vector',
    '임베딩': 'embedding',
    '인덱싱': 'indexing',
    '집계': 'aggregation',
    '조인': 'join',
    '유니온': 'union',
    '서브쿼리': 'subquery',
    '윈도우함수': 'window-function',
    '프로시저': 'procedure',
    '함수': 'function',
    '뷰': 'view',
    '구체화된뷰': 'materialized-view',
    '파티셔닝': 'partitioning',
    '샤딩': 'sharding',
    '레플리카': 'replica',
    '마스터': 'master',
    '슬레이브': 'slave',
    '프라이머리': 'primary',
    '세컨더리': 'secondary',
    '읽기전용': 'read-only',
    '쓰기전용': 'write-only',
    '읽기쓰기': 'read-write',
    '뉴스레터': 'newsletter',
    '블로그': 'blog',
    '기타': 'etc',
    '5': 'five',
    '10': 'ten',
    '1': 'one',
    '2': 'two',
    '3': 'three',
    '4': 'four',
    '6': 'six',
    '7': 'seven',
    '8': 'eight',
    '9': 'nine'
  }

  // Clean the text
  let cleanedText = text.trim().toLowerCase()
  
  // Replace Korean words with English equivalents
  Object.entries(koreanToEnglish).forEach(([korean, english]) => {
    const regex = new RegExp(korean, 'gi')
    cleanedText = cleanedText.replace(regex, ` ${english} `)
  })
  
  // Clean up the result
  cleanedText = cleanedText
    .replace(/[^a-z0-9\s-]/g, '') // Remove non-alphanumeric characters
    .replace(/\s+/g, '-') // Replace spaces with hyphens
    .replace(/-+/g, '-') // Replace multiple hyphens with single hyphen
    .replace(/^-+|-+$/g, '') // Remove leading/trailing hyphens
  
  // If the result is empty or too short, generate a fallback
  if (!cleanedText || cleanedText.length < 3) {
    // Generate a random ID for uniqueness
    const timestamp = Date.now().toString(36)
    cleanedText = `post-${timestamp}`
  }
  
  // Limit slug length
  if (cleanedText.length > 100) {
    cleanedText = cleanedText.substring(0, 100).replace(/-+$/, '')
  }
  
  return cleanedText
}

/**
 * Generate a romanized slug from Korean text
 * Converts Korean to English characters for better URL compatibility
 */
export function generateRomanizedSlug(text: string): string {
  return generateKoreanSlug(text) // Now both functions do the same thing
}

/**
 * Normalize a slug for comparison
 * Handles variations in slug format
 */
export function normalizeSlug(slug: string): string {
  return slug
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9\-]/g, '')
    .replace(/--+/g, '-')
    .replace(/^-|-$/g, '')
}

/**
 * Check if two slugs are equivalent
 */
export function slugsMatch(slug1: string, slug2: string): boolean {
  return normalizeSlug(slug1) === normalizeSlug(slug2)
}